language: node_js
node_js:
- 4.4.3
sudo: required
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - bash scripts/ci-support.sh
  - sleep 3
script:
  - xvfb-run gulp test:ci
  - node_modules/.bin/codecov
deploy:
  provider: npm
  email: maurizio.cas@gmail.com
  api_key:
    secure: IsXTjqdxaByIttOU5yyPiFcQkqGD2F/+opjoKQ6ujjc5uYkUa3gy82ZeSk479RE/tnhGuwcVOFtMLBwhqY5Xb0jq5sAStG616YN7JAYiUtX32bPEgnCT77ZlTgoUp8vhO3Cl5XXOOjLR/99jVJUPem6ury41RghjC9r/aHNJluA=
  on:
    tags: true
    repo: mcasimir/mobile-angular-ui
cache:
  directories:
    - node_modules
