language: node_js
node_js:
- '0.11'
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install codecov
  - npm install

after_success:
  - codecov

script: node_modules/.bin/gulp test:ci
