language: node_js
node_js:
- 4.4.3
sudo: required
before_install:
- sudo apt-get update
- sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
services:
- docker
script:
- docker run --rm --privileged -w /usr/src/app -v $PWD:/usr/src/app mcasimir/dind-node-build-runner:4.4.3 bash ci.sh
- node_modules/.bin/codecov
deploy:
  provider: npm
  email: maurizio.cas@gmail.com
  api_key:
    secure: IsXTjqdxaByIttOU5yyPiFcQkqGD2F/+opjoKQ6ujjc5uYkUa3gy82ZeSk479RE/tnhGuwcVOFtMLBwhqY5Xb0jq5sAStG616YN7JAYiUtX32bPEgnCT77ZlTgoUp8vhO3Cl5XXOOjLR/99jVJUPem6ury41RghjC9r/aHNJluA=
  on:
    tags: true
    repo: mcasimir/mobile-angular-ui
